# Generated by Django 4.2.7 on 2025-09-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.JSONField(default=list, help_text='For organization and AI analysis'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferences',
            field=models.JSONField(default=dict, help_text='Learning preferences'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='strengths',
            field=models.JSONField(default=list, help_text='Strong subject areas'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='weaknesses',
            field=models.JSONField(default=list, help_text='Areas needing improvement'),
        ),
    ]
