
# Generated by Django 4.2.7 on 2025-09-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_external_id_course_external_platform'),
        ('users', '0005_user_date_of_birth_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='available_for_new_students',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='average_rating',
            field=models.FloatField(default=0.0, help_text='Average rating from students'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='certifications',
            field=models.JSONField(default=list, help_text='Professional certifications'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Professional contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='education_background',
            field=models.TextField(blank=True, help_text='Educational qualifications'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='expertise_areas',
            field=models.JSONField(default=list, help_text='List of specific expertise areas within subjects'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='languages',
            field=models.JSONField(default=list, help_text='Languages teacher can teach in'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='last_training_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='max_students_per_class',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='office_hours',
            field=models.JSONField(default=dict, help_text='Weekly office hours schedule'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='preferred_class_size',
            field=models.IntegerField(default=15, help_text='Preferred number of students'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='professional_development',
            field=models.JSONField(default=list, help_text='Recent training and development activities'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, help_text='Subjects this teacher can teach', related_name='teachers', to='courses.subject'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='success_rate',
            field=models.FloatField(default=0.0, help_text='Percentage of students who pass'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_methods',
            field=models.JSONField(default=list, help_text='Preferred teaching methods (e.g., visual, hands-on, discussion-based)'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='title',
            field=models.CharField(blank=True, help_text='e.g., Dr., Prof., Mr., Ms.', max_length=50),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='total_classes_conducted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='total_students_taught',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['teaching_status', 'available_for_new_students'], name='teacher_pro_teachin_ae935d_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['average_rating'], name='teacher_pro_average_fdf3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['experience_years'], name='teacher_pro_experie_915157_idx'),
        ),
    ]
