# Generated by Django 4.2.7 on 2025-09-08 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '__first__'),
        ('users', '0007_dailyquoteassignment_goal_milestonereward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedchathistory',
            name='original_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_versions', to='chatbot.chatsession'),
        ),
    ]
