# Generated by Django 4.2.7 on 2025-09-09 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_savedchathistory_original_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document')], max_length=10)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('extracted_text', models.TextField(blank=True, help_text='Full text extracted from document')),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary')),
                ('summary_metadata', models.JSONField(default=dict, help_text='Metadata about summary generation')),
                ('title', models.CharField(blank=True, help_text='User-defined title', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(default=list, help_text='User-defined tags')),
                ('notes', models.TextField(blank=True, help_text='User notes about the document')),
                ('is_favorite', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_summaries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='document_su_user_id_6bf5e8_idx'), models.Index(fields=['status'], name='document_su_status_c6fc67_idx'), models.Index(fields=['file_type'], name='document_su_file_ty_b6de49_idx')],
            },
        ),
    ]
