# Generated by Django 4.2.7 on 2025-09-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_documentsummary'),
    ]

    operations = [
        migrations.RunSQL(
            """
            SET @column_exists = (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_NAME = 'goals' 
                AND COLUMN_NAME = 'user_id' 
                AND TABLE_SCHEMA = DATABASE()
            );
            SET @sql = IF(@column_exists = 0,
                'ALTER TABLE goals ADD COLUMN user_id BIGINT, ADD CONSTRAINT goals_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE',
                'SELECT "Column already exists" as message'
            );
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="""
            SET @column_exists = (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_NAME = 'goals' 
                AND COLUMN_NAME = 'user_id' 
                AND TABLE_SCHEMA = DATABASE()
            );
            SET @sql = IF(@column_exists = 1,
                'ALTER TABLE goals DROP FOREIGN KEY goals_user_fk, DROP COLUMN user_id',
                'SELECT "Column does not exist" as message'
            );
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """
        ),
    ]
