# Generated by Django 4.2.7 on 2025-09-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20250910_1546'),
    ]

    operations = [
        # Fix saved_chat_history table
        migrations.RunSQL(
            """
            SET @column_exists = (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_NAME = 'saved_chat_history' 
                AND COLUMN_NAME = 'user_id' 
                AND TABLE_SCHEMA = DATABASE()
            );
            SET @sql = IF(@column_exists = 0,
                'ALTER TABLE saved_chat_history ADD COLUMN user_id BIGINT, ADD CONSTRAINT saved_chat_history_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE',
                'SELECT "Column already exists" as message'
            );
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="""
            SET @column_exists = (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_NAME = 'saved_chat_history' 
                AND COLUMN_NAME = 'user_id' 
                AND TABLE_SCHEMA = DATABASE()
            );
            SET @sql = IF(@column_exists = 1,
                'ALTER TABLE saved_chat_history DROP FOREIGN KEY saved_chat_history_user_fk, DROP COLUMN user_id',
                'SELECT "Column does not exist" as message'
            );
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """
        ),
        # Fix notes table
        migrations.RunSQL(
            """
            SET @column_exists = (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_NAME = 'notes' 
                AND COLUMN_NAME = 'user_id' 
                AND TABLE_SCHEMA = DATABASE()
            );
            SET @sql = IF(@column_exists = 0,
                'ALTER TABLE notes ADD COLUMN user_id BIGINT, ADD CONSTRAINT notes_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE',
                'SELECT "Column already exists" as message'
            );
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="""
            SET @column_exists = (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_NAME = 'notes' 
                AND COLUMN_NAME = 'user_id' 
                AND TABLE_SCHEMA = DATABASE()
            );
            SET @sql = IF(@column_exists = 1,
                'ALTER TABLE notes DROP FOREIGN KEY notes_user_fk, DROP COLUMN user_id',
                'SELECT "Column does not exist" as message'
            );
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """
        ),
        # Fix daily_quote_assignments table
        migrations.RunSQL(
            """
            SET @column_exists = (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_NAME = 'daily_quote_assignments' 
                AND COLUMN_NAME = 'user_id' 
                AND TABLE_SCHEMA = DATABASE()
            );
            SET @sql = IF(@column_exists = 0,
                'ALTER TABLE daily_quote_assignments ADD COLUMN user_id BIGINT, ADD CONSTRAINT daily_quote_assignments_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE',
                'SELECT "Column already exists" as message'
            );
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="""
            SET @column_exists = (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_NAME = 'daily_quote_assignments' 
                AND COLUMN_NAME = 'user_id' 
                AND TABLE_SCHEMA = DATABASE()
            );
            SET @sql = IF(@column_exists = 1,
                'ALTER TABLE daily_quote_assignments DROP FOREIGN KEY daily_quote_assignments_user_fk, DROP COLUMN user_id',
                'SELECT "Column does not exist" as message'
            );
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """
        ),
        # Fix milestone_rewards table
        migrations.RunSQL(
            """
            SET @column_exists = (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_NAME = 'milestone_rewards' 
                AND COLUMN_NAME = 'user_id' 
                AND TABLE_SCHEMA = DATABASE()
            );
            SET @sql = IF(@column_exists = 0,
                'ALTER TABLE milestone_rewards ADD COLUMN user_id BIGINT, ADD CONSTRAINT milestone_rewards_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE',
                'SELECT "Column already exists" as message'
            );
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="""
            SET @column_exists = (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_NAME = 'milestone_rewards' 
                AND COLUMN_NAME = 'user_id' 
                AND TABLE_SCHEMA = DATABASE()
            );
            SET @sql = IF(@column_exists = 1,
                'ALTER TABLE milestone_rewards DROP FOREIGN KEY milestone_rewards_user_fk, DROP COLUMN user_id',
                'SELECT "Column does not exist" as message'
            );
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """
        ),
        # Fix document_summaries table
        migrations.RunSQL(
            """
            SET @column_exists = (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_NAME = 'document_summaries' 
                AND COLUMN_NAME = 'user_id' 
                AND TABLE_SCHEMA = DATABASE()
            );
            SET @sql = IF(@column_exists = 0,
                'ALTER TABLE document_summaries ADD COLUMN user_id BIGINT, ADD CONSTRAINT document_summaries_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE',
                'SELECT "Column already exists" as message'
            );
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="""
            SET @column_exists = (
                SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_NAME = 'document_summaries' 
                AND COLUMN_NAME = 'user_id' 
                AND TABLE_SCHEMA = DATABASE()
            );
            SET @sql = IF(@column_exists = 1,
                'ALTER TABLE document_summaries DROP FOREIGN KEY document_summaries_user_fk, DROP COLUMN user_id',
                'SELECT "Column does not exist" as message'
            );
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """
        ),
    ]
