# Generated by Django 4.2.7 on 2025-09-07 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_course_external_id_course_external_platform'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text="Student's message explaining why they want to enroll")),
                ('preferred_schedule', models.JSONField(default=dict, help_text="Student's preferred class schedule")),
                ('learning_goals', models.TextField(blank=True, help_text='What the student hopes to achieve')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('teacher_response', models.TextField(blank=True, help_text="Teacher's response to the request")),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, help_text='Specific classroom if requesting to join existing class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='progress.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(help_text='Subject the student wants to learn', on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrollment_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='enrollment__student_f9b824_idx'), models.Index(fields=['teacher', 'status'], name='enrollment__teacher_b33d05_idx'), models.Index(fields=['created_at'], name='enrollment__created_e76764_idx')],
            },
        ),
    ]
