# Generated by Django 4.2.7 on 2025-09-07 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0003_assignment_tasksubmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('enrollment_request', 'Enrollment Request'), ('enrollment_approved', 'Enrollment Approved'), ('enrollment_rejected', 'Enrollment Rejected'), ('assignment_created', 'New Assignment'), ('assignment_due_soon', 'Assignment Due Soon'), ('assignment_overdue', 'Assignment Overdue'), ('assignment_graded', 'Assignment Graded'), ('class_created', 'Class Created'), ('student_joined', 'Student Joined Class'), ('student_removed', 'Student Removed from Class'), ('system_message', 'System Message'), ('achievement', 'Achievement Unlocked'), ('reminder', 'Reminder'), ('announcement', 'Announcement')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (assignment, enrollment_request, etc.)', max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional data for the notification (links, actions, etc.)')),
                ('action_url', models.CharField(blank=True, help_text='URL for primary action (e.g., view assignment, approve request)', max_length=500)),
                ('action_label', models.CharField(blank=True, help_text='Label for primary action button', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this notification becomes irrelevant (optional)', null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='User who triggered this notification (can be null for system notifications)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['type', 'priority'], name='notificatio_type_7e50f5_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_66996e_idx')],
            },
        ),
    ]
