# Generated by Django 4.2.7 on 2025-09-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classenrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='classenrollment',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='classenrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='teacher',
        ),
        migrations.AlterUniqueTogether(
            name='tasksubmission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='graded_by',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='student',
        ),
        migrations.RemoveField(
            model_name='learninggoal',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='performanceanalytics',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='ClassEnrollment',
        ),
        migrations.DeleteModel(
            name='ClassRoom',
        ),
        migrations.DeleteModel(
            name='EnrollmentRequest',
        ),
        migrations.DeleteModel(
            name='TaskSubmission',
        ),
    ]
