# Generated by Django 4.2.7 on 2025-09-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_question_quiz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['course', '-created_at']},
        ),
        migrations.AddField(
            model_name='quiz',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='Generated by AI based on student weaknesses'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='attempts_allowed',
            field=models.IntegerField(default=1, help_text='Number of attempts allowed (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Quiz becomes available from this date', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='available_until',
            field=models.DateTimeField(blank=True, help_text='Quiz available until this date', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_results_immediately',
            field=models.BooleanField(default=True, help_text='Show results after submission'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffle_options',
            field=models.BooleanField(default=False, help_text='Randomize answer options'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffle_questions',
            field=models.BooleanField(default=False, help_text='Randomize question order'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='target_concepts',
            field=models.JSONField(default=list, help_text='Concepts this quiz targets'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=0, help_text='Time limit in minutes (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.FloatField(default=70.0, help_text='Minimum score to pass (0-100)'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['course', 'is_active'], name='quizzes_course__6a0c35_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['ai_generated', 'difficulty_level'], name='quizzes_ai_gene_cc805f_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['available_from', 'available_until'], name='quizzes_availab_e3a10c_idx'),
        ),
    ]
