# Generated by Django 4.2.7 on 2025-09-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_quiz_options_quiz_ai_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_id',
            field=models.CharField(blank=True, help_text='Course ID in the external platform', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='external_platform',
            field=models.CharField(blank=True, choices=[('moodle', 'Moodle'), ('coursera', 'Coursera'), ('lti', 'LTI')], help_text='External platform this course is synced from', max_length=50, null=True),
        ),
    ]
