# Generated by Django 4.2.7 on 2025-09-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_external_id_course_external_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='ai_tutor_avatar',
            field=models.CharField(default='AI', help_text='Avatar for AI tutor', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='ai_tutor_name',
            field=models.CharField(default='AI Tutor', help_text='Name of AI tutor for this course', max_length=100),
        ),
    ]
