# Generated by Django 4.2.7 on 2025-09-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_instructor_course_ai_tutor_avatar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseEnrollment',
        ),
    ]
